### ISSUE TITLE
Problem build MayaPartioTools in Windows

### ISSUE THREAD

**Issue by sulthanAZ** [InteractiveComputerGraphics/MayaPartioTools#1]
first I want to apologize for my lack of knowledge in this matter, I experienced an error in build MayaPartioTools in windows, I will attach the error in the picture. I installed with this following steps:
1. I cloned your git repository
2. then I build it with cmake base windows version 3.17 and I select output Visual Studio 16 2019
4. when I debug on VS, the result is an error due to the lost  of some files.

first is my step right? then is there really a lack of files in my clone?

thank you in advance, sorry for my lack of knowledge.
![image](https://user-images.githubusercontent.com/61886425/76116366-736b8b00-601c-11ea-88fc-ff0294f4d3f3.png)
![image](https://user-images.githubusercontent.com/61886425/76116819-381d8c00-601d-11ea-82ad-53ed4ccf8f07.png)

**Comment by janbender** [comment]
DId you install the Maya SDK on your system?

**Comment by sulthanAZ** [comment]
I have not installed the Maya SDK, it seems I see my problem. I will try to install the Maya SDK first and try to build it again. can I use all of the Maya SDK versions? or only a certain version? thank you for your response to my problem.

**Comment by janbender** [comment]
Use the one for your Maya version.

**Comment by janbender** [comment]
https://www.autodesk.com/developer-network/platform-technologies/maya

**Comment by sulthanAZ** [comment]
thank you for helping me. sorry for my lack of knowledge on this matter.
